using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Filters;

namespace SensitiveWords.Api.Swagger.Examples
{
    /// <summary>
    /// Returns an example of a Bad Request response, typically used to illustrate the structure of error responses in API documentation generated by Swagger or similar tools. The example includes a title, status code, and detail message to help developers understand what a typical 400 Bad Request response might look like when the client sends an invalid request payload.
    /// </summary>
    public class BadRequestExample : IExamplesProvider<ProblemDetails>
    {
        /// <summary>
        /// Returns an example instance of the ProblemDetails class representing a typical invalid request error.
        /// </summary>
        /// <returns>A ProblemDetails object with sample values for Title, Status, and Detail properties, illustrating a 400 Bad
        /// Request error.</returns>
        public ProblemDetails GetExamples()
        {
            return new ProblemDetails
            {
                Title = "Invalid request",
                Status = 400,
                Detail = "The request is invalid."
            };
        }
    }
}
